### ISSUE TITLE
URL path parts for section content

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#172]
When clicking on a section in the left nav, content loads. However, the URL doesn't accurately (from a user perspective) reflect the "path" and exposes the underlying implementation details.

For example, open a browser tab, and go to this page: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/content-collections/governance/governance

From the left nav, the path to the page appears to be: `Enterprise Edition > Content Collections > Governance`

However, the URL  path is `enterprise-edition/content-collections/governance/governance`

The URL path should be `enterprise-edition/content-collections/governance`

**Comment by maxakuru** [comment]
there are a few ways to change this, but I think the most maintainable would be to use redirects from the `prisma-cloud-docs` repo and just change the frontend urls.. 

example: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/governance
redirects file: https://github.com/hlxsites/prisma-cloud-docs/blob/main/redirects.json

wdyt @iansk?

**Comment by iansk** [comment]
@maxakuru What other options are there? We have tons of sections, and we're constantly refactoring content. It's going to be a headache on our side to continually maintain and update the redirects file. Is there an automatic way to handle this?

**Comment by maxakuru** [comment]
to automate it, the `redirects.json` could be built via a github action on merges to main, just like how sitemaps are generated & pushed

the other option is to build the required data into the worker & change the worker code to conditionally redirect requests to the "double end segment" version.. imo, that's a bit too much magic and would be difficult to debug. Having the list of redirects that are active there in code on the main branch would make debugging simple

**Comment by maxakuru** [comment]
I made a script that will generate redirects for topics that have the same path segment as their parent, you can see the output here: https://github.com/hlxsites/prisma-cloud-docs/blob/maxed/scripts/redirects.json

that combined with a tweak to how we create the sidenav links (#189) should fix this

**Comment by iansk** [comment]
@maxakuru I'm concerned about how this will impact previews. As you know, I want previews to be rock solid, and fully reflect what you see in your preview will be what you see when you merge into main. Given that there is one redirects file, and there can be multiple branches with different/conflicting book.yml's, I think that this can get pretty messy pretty quickly.

Instead of the redirects, would refactoring book.yml be better?

```
kind: chapter
name: Connect
dir: connect
topics:
  - name: Connect
    file: connect.adoc
  - name: Connect Cloud Accounts
    dir: connect-cloud-accounts
    topics:
      - name: Connect Cloud Accounts
        file: connect-cloud-accounts.adoc
     - name: Onboard Your AWS Organization
        file: onboard-aws-org.adoc
      - name: Onboard Your AWS Account
        file: onboard-aws-account.adoc
```

Right now, we do a little magic under the hood in the left nav. For example, `connect-cloud-accounts.adoc` is hidden in the left nav, and rendered when you click the section drop-down "Connect Cloud Accounts". If we restructued the book.yml to better reflect what we want to do, could we fix the double `connect-cloud-accounts/connect-cloud-accounts` shown in the URL?
