### ISSUE TITLE
Left nav - section entries

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#40]
Clicking on an expandable entry in the left nav doesn't show any content.

For example, see "Install" on Franklin: [Prisma Cloud Administrator’s Guide (Compute)](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/install)

<img width="1469" alt="left-nev-section-entry-franklin" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/2bfa07ef-79b0-4b97-9cf5-8699a77abfb3">

See "Install" on AEM: https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/install

<img width="1471" alt="left-nav-section-entry-aem" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/82826e6b-bcd5-488b-93e2-b3160a9b3443">

If you look at the [book.yml](https://github.com/hlxsites/prisma-cloud-docs/blob/main/docs/en/compute/30-xx/admin-guide/book.yml) file, you'll see how it works. The section/chapter dir is `install`. The first topic is named `install.adoc`, and it's what should be displayed/rendered when someone clicks on the "Install" expandable entry.

```
---
kind: chapter
name: Install
dir: install
topics:
- name: Install
  file: install.adoc
- name: Getting started
  file: getting_started.adoc
- name: System requirements
```
